export const DRIP_ABI = [
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "_src", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "_dest",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_deposits",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_payouts",
        type: "uint256",
      },
    ],
    name: "BalanceTransfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
    ],
    name: "BeneficiaryUpdate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "Checkin",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      { indexed: true, internalType: "address", name: "from", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "DirectPayout",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "HeartBeat",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "interval",
        type: "uint256",
      },
    ],
    name: "HeartBeatIntervalUpdate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "referrals",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "total_deposits",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "total_payouts",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "total_structure",
        type: "uint256",
      },
    ],
    name: "Leaderboard",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "LimitReached",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "manager",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "ManagerUpdate",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      { indexed: true, internalType: "address", name: "from", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "MatchPayout",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "NewAirdrop",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "NewDeposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      {
        indexed: true,
        internalType: "address",
        name: "upline",
        type: "address",
      },
    ],
    name: "Upline",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "addr", type: "address" },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "Withdraw",
    type: "event",
  },
  { stateMutability: "payable", type: "fallback" },
  {
    inputs: [],
    name: "CompoundTax",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ExitTax",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_UINT",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_to", type: "address" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "airdrop",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "airdrops",
    outputs: [
      { internalType: "uint256", name: "airdrops", type: "uint256" },
      { internalType: "uint256", name: "airdrops_received", type: "uint256" },
      { internalType: "uint256", name: "last_airdrop", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_addr", type: "address" }],
    name: "balanceLevel",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "checkin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_addr", type: "address" }],
    name: "claimsAvailable",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "contractInfo",
    outputs: [
      { internalType: "uint256", name: "_total_users", type: "uint256" },
      { internalType: "uint256", name: "_total_deposited", type: "uint256" },
      { internalType: "uint256", name: "_total_withdraw", type: "uint256" },
      { internalType: "uint256", name: "_total_bnb", type: "uint256" },
      { internalType: "uint256", name: "_total_txs", type: "uint256" },
      { internalType: "uint256", name: "_total_airdrops", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_addr", type: "address" }],
    name: "creditsAndDebits",
    outputs: [
      { internalType: "uint256", name: "_credits", type: "uint256" },
      { internalType: "uint256", name: "_debits", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "custody",
    outputs: [
      { internalType: "address", name: "manager", type: "address" },
      { internalType: "address", name: "beneficiary", type: "address" },
      { internalType: "uint256", name: "last_heartbeat", type: "uint256" },
      { internalType: "uint256", name: "last_checkin", type: "uint256" },
      { internalType: "uint256", name: "heartbeat_interval", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_upline", type: "address" },
      { internalType: "uint256", name: "_amount", type: "uint256" },
    ],
    name: "deposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "deposit_bracket_size",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "dripVaultAddress",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_addr", type: "address" }],
    name: "getCustody",
    outputs: [
      { internalType: "address", name: "_beneficiary", type: "address" },
      { internalType: "uint256", name: "_heartbeat_interval", type: "uint256" },
      { internalType: "address", name: "_manager", type: "address" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_addr", type: "address" },
      { internalType: "uint8", name: "_level", type: "uint8" },
    ],
    name: "isBalanceCovered",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_addr", type: "address" }],
    name: "isNetPositive",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_addr", type: "address" }],
    name: "lastActivity",
    outputs: [
      { internalType: "uint256", name: "_heartbeat", type: "uint256" },
      { internalType: "uint256", name: "_lapsed_heartbeat", type: "uint256" },
      { internalType: "uint256", name: "_checkin", type: "uint256" },
      { internalType: "uint256", name: "_lapsed_checkin", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_amount", type: "uint256" }],
    name: "maxPayoutOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "max_payout_cap",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_addr", type: "address" }],
    name: "payoutOf",
    outputs: [
      { internalType: "uint256", name: "payout", type: "uint256" },
      { internalType: "uint256", name: "max_payout", type: "uint256" },
      { internalType: "uint256", name: "net_payout", type: "uint256" },
      { internalType: "uint256", name: "sustainability_fee", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "ref_balances",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "roll",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "_addr", type: "address" },
      { internalType: "uint256", name: "_pendingDiv", type: "uint256" },
    ],
    name: "sustainabilityFeeV2",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "total_airdrops",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "total_bnb",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "total_deposited",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "total_txs",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "total_users",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "total_withdraw",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newCompoundTax", type: "uint256" },
    ],
    name: "updateCompoundTax",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newBracketSize", type: "uint256" },
    ],
    name: "updateDepositBracketSize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_newExitTax", type: "uint256" }],
    name: "updateExitTax",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256[]", name: "_newRefBalances", type: "uint256[]" },
    ],
    name: "updateHoldRequirements",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newInitialDeposit", type: "uint256" },
    ],
    name: "updateInitialDeposit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newPayoutCap", type: "uint256" },
    ],
    name: "updateMaxPayoutCap",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newPayoutRate", type: "uint256" },
    ],
    name: "updatePayoutRate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newRefBonus", type: "uint256" },
    ],
    name: "updateRefBonus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_newRefDepth", type: "uint256" },
    ],
    name: "updateRefDepth",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_addr", type: "address" }],
    name: "userInfo",
    outputs: [
      { internalType: "address", name: "upline", type: "address" },
      { internalType: "uint256", name: "deposit_time", type: "uint256" },
      { internalType: "uint256", name: "deposits", type: "uint256" },
      { internalType: "uint256", name: "payouts", type: "uint256" },
      { internalType: "uint256", name: "direct_bonus", type: "uint256" },
      { internalType: "uint256", name: "match_bonus", type: "uint256" },
      { internalType: "uint256", name: "last_airdrop", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "_addr", type: "address" }],
    name: "userInfoTotals",
    outputs: [
      { internalType: "uint256", name: "referrals", type: "uint256" },
      { internalType: "uint256", name: "total_deposits", type: "uint256" },
      { internalType: "uint256", name: "total_payouts", type: "uint256" },
      { internalType: "uint256", name: "total_structure", type: "uint256" },
      { internalType: "uint256", name: "airdrops_total", type: "uint256" },
      { internalType: "uint256", name: "airdrops_received", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "users",
    outputs: [
      { internalType: "address", name: "upline", type: "address" },
      { internalType: "uint256", name: "referrals", type: "uint256" },
      { internalType: "uint256", name: "total_structure", type: "uint256" },
      { internalType: "uint256", name: "direct_bonus", type: "uint256" },
      { internalType: "uint256", name: "match_bonus", type: "uint256" },
      { internalType: "uint256", name: "deposits", type: "uint256" },
      { internalType: "uint256", name: "deposit_time", type: "uint256" },
      { internalType: "uint256", name: "payouts", type: "uint256" },
      { internalType: "uint256", name: "rolls", type: "uint256" },
      { internalType: "uint256", name: "ref_claim_pos", type: "uint256" },
      { internalType: "uint256", name: "accumulatedDiv", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export const DRIP_ADDR = "0xFFE811714ab35360b67eE195acE7C10D93f89D8C";

export const myWallets = [
  0x1ff661243cb97384102a69a466c887b4cc12d72a,
  0xb066550524e791c41672178975febb4e7038a3f8,
  0x2d796203fe2029eba04d5f7994870bb78251ddba,
  0x3a77bde3928e2a995823d9abcc6224c1998b560f,
  0x13a76726ae59e9cd3505b9cba750c774d1c18be0,
  0x56e11397f315a8f3136e673b43a152e400aa270a,
  0x5749f135542d7dfd842c3dda627b2b6da2d8298a,
  0x0e833a659bb581721d1296c87d26a3afb3dfc33d,
  0x3b567c88bb82c2bf40a6c3512c859493f34eabba,
  0x9e11479f26321565b6a7ceb4a3c81a6ca2c2166f,
  0x1be1df3cc70bc4d912450406c4d52984a1d6f223,
  0x0f4b20bb131e9cb6e19bfae5c86c4e0cb54d52e4,
  0x3627c873ccb0c4d1c725d544a5ac3b99684cb318,
  0x6befe7cfdbb5cd3e8ff142028294e339c210b5d8,
  0xe1e0571b5fe201b4fffcbbed18ffdb68b40d555c,
  0xe269ea59f63bf29785d1adb0fb1124557ce5d4e9,
  0x4c47fc7d8927661a39323c769af4b66639126eda,
  0xe987992e7cea28ff375cc2fcce8db697ee7c643a,
  0x8f6ad82d5c3c94d4d9391e00c0c1c615f536980e,
  0x23201cd358f519fd4e63bf6eb576a9d2b9831a4a,
  0xaabac7f3ae4f8ebe7a2385431fa8d0d487017f2d,
];
